### ISSUE TITLE
Unknown artifact

### ISSUE THREAD

**Issue by AndreaCrotti** [clojure-grimoire/grimoire#202] opened 2015-05-02 07:00 UTC
In the API documentation as pasted below I think there are a couple of issues..

1. all these urls complain about "unknown artifact", the problem seems simply that there is "v0" instead of "v1"
2. the type is specified as TYPE the first two examples and ?type=text/plain in the third..

Is it safe correct to just change the examples to 
GET http://conj.io/store/v1/org.clojure/clojure/1.6.0/clojure.core/conj/?type=text/html
Instead?

GET http://conj.io/store/v0/org.clojure/clojure/1.6.0/clojure.core/conj/ TYPE: text/html shall return HTML formatted documentation of clojure.core/conj as of the release of [org.clojure/clojure "1.6.0"] as per convention.

GET http://conj.io/store/v0/org.clojure/clojure/1.6.0/clojure.core/conj/ TYPE: text/plain shall return plain text or un-rendered markdown documentation of clojure.core/conj as of [org.clojure/clojure "1.6.0"] formatted for an 80-character display.

GET http://conj.io/store/v0/org.clojure/clojure/1.6.0/clojure.core/conj/?type=text/plain shall give the same result as if the type header were set to text/plain.

**Comment by arrdem** [comment] 2015-05-02 07:19
Ugh add one to the list of reasons why I need a test suite.

Yes. Store v0 is deprecated but shouldn't be broken. v1 should work just fine. I'll get the examples fixed, thanks for the ticket.

**Comment by arrdem** [comment] 2015-05-02 17:34
As to the `/?type=text/plain`, both `-H "Content-Type: text/plain" and `/?type=text/plain` should behave the same. Sorry I didn't see that initially.

**Comment by semperos** [comment] 2015-06-04 04:29
I don't believe the issue is `v0` vs `v1`, but rather that part of the path is missing in the API documentation.

This example from the [api docs](http://conj.io/api):

`GET http://conj.io/store/v0/org.clojure/clojure/1.6.0/clojure.core/conj/ TYPE: text/plain`

Returns an `Unknown artifact version "1.6.0"` error response. The example should read:

`GET http://conj.io/store/v0/org.clojure/clojure/1.6.0/clj/clojure.core/conj/ TYPE: text/plain`

Note the additional `.../clj/...` part of the path. This seems to be what is missing in URL's as they appear in the documentation. This works for both `v0` and `v1`.

_Side note/My $0.02: It would likely be more useful to write out the examples with simple `curl -L ... -H "Content-Type: ..."` invocations so folks reading the docs can copy and paste to see them in action._

**Comment by arrdem** [comment] 2015-06-04 04:32
@semperos thanks for the note. That the examples are out of date is well known, the latter being v1 paths, but v0 URLs *should* still work without the clj part.

I'll definitely use curl commands when I rewrite the examples tho.

**Comment by arrdem** [comment] 2015-06-15 22:50
Okay so the problem that @semperos pointed out with the `/clj/` platform selector being missing (and not added by the rout upgrading) should be fixed by the above. The `/clj/` platform selector was the primary cause of the v0 -> v1 bump, and is _not_ required in v0 style URLs.

I'll get the API documentation updated and reformated with CURL examples, but I think that does it for this issue.

**Closed by arrdem** 2015-06-15 22:50 UTC
