### ISSUE TITLE
.. link is broken

### ISSUE THREAD

**Issue by RadicalZephyr** [clojure-grimoire/grimoire#203] opened 2015-05-29 15:39 UTC
Even though it's literally `store/v1/org.clojure/clojure/latest/clj/clojure.core/%2E%2E/` 
Currently it's resolving to `store/v1/org.clojure/clojure/1.7.0-alpha4/clj/` 

This is understandable, but highly confusing from a user perspective.

**Comment by arrdem** [comment] 2015-05-29 17:50
Thanks for the report, where are you encountering this? On the front page I assume.

**Comment by RadicalZephyr** [comment] 2015-05-29 20:21
Yup, front page.

**Comment by arrdem** [comment] 2015-05-29 23:18
Okay. I'll try and get this fixed in a bit... it's a bug in the URL forging of the /latest/ resolution handler.

**Comment by arrdem** [comment] 2015-06-15 22:25
```
% curl -IL http://127.0.0.1:3000/store/v1/org.clojure/clojure/latest/clj/clojure.core/%2E%2E/
HTTP/1.1 301 Moved Permanently
Date: Mon, 15 Jun 2015 22:24:24 GMT
Location: /store/v1/org.clojure/clojure/1.7.0-alpha4/clj/clojure.core/%2E%2E/
Content-Length: 0
Server: Jetty(7.6.13.v20130916)

HTTP/1.1 200 OK
Date: Mon, 15 Jun 2015 22:24:24 GMT
Content-Type: text/html;charset=UTF-8
Content-Length: 0
Server: Jetty(7.6.13.v20130916)
```

Hum... could not reproduce. Can you add more information?

**Comment by arrdem** [comment] 2015-06-15 22:44
You wouldn't happen to be on Chrom[e|ium] would you? I'm seeing this behavior on those browsers but not on Firefox and some others. Looks like a client issue due to my (ab)use of the %2e encoding of \. which isn't actually spec defined.

**Comment by RadicalZephyr** [comment] 2015-06-16 16:14
Definitely am.  Didn't think to test it on a different browser.

**Comment by arrdem** [comment] 2015-06-16 16:52
Okay. I'll chew on how to "fix" this. `(urlencode ".") => "."`, which doesn't work so well for `".."`. The fix I came up with was to abuse the fact that URL encoding is really just a % prefixed hex number, so I can say `"%2E%2E"` which will url _decode_ correctly to `".."` but not being `".."` should prevent clients from doing exactly what chrome seems to happily do here. Strictly speaking Chrome isn't doing the wrong thing because %2E is a nonstandard encoding, however in order to work around this I would have to introduce a significantly more involved munging function when I just went through a bunch of compatibility drama to get rid of my previous nonstandard munging operation.

**Comment by arrdem** [comment] 2015-06-18 00:52
http://tools.ietf.org/html/rfc3986#section-5.2.4

fek

**Comment by arrdem** [comment] 2015-06-18 01:50
Okay so rfc3986 says nothing about rewriting `"/a/%2E%2E/" -> "/a/.." -> "/"`. Closing this as a very unfortunate client issue.

**Closed** 2015-06-18 01:50 UTC
Labels: bug

**Comment by RadicalZephyr** [comment] 2015-06-18 01:56
Fair enough.  FWIW the clojure.org cheatsheet simply maps the `..` method to `_dot_dot`.

**Comment by arrdem** [comment] 2015-06-18 01:57
Yeah I used to do something like that... I may yet hack it back in.
